### PR TITLE
32 design of the ban interface and new users interface finish 

### PR DESCRIPTION
**Pull request by Uli19**
<============== New user verification and ban view finished ===========>

This release reflects changes in the styles of the ban and user verification views

The elements within this view were given new styles and structure, adding color, shapes, icons and new spaces for a favorable experience within the views, a new function was also added that makes an element detachable, in addition to a google function so that user images are round

Why are these changes necessary?
To have a good way of presentation and also for the user experience, it is also a significant change for the app

How have these changes been tested?
Tests have been done within the team, testing the app to make it work well

<============== Visual Information ===========>

### CODE REVIEW

**Review by Kamila04 — APPROVED** [review]

**Review by Gavalencia12 — APPROVED** [review]
The application is in English, but the design is good.

**Review by Angel591Diaz — APPROVED** [review]

**Review by MeganPegueros — APPROVED** [review]
Good

**Comment by IsmaelMontiel710** [comment]
Why is the ID printed when displaying the users?"

**Review by IsmaelMontiel710 — CHANGES_REQUESTED** [review]
Why is the ID printed when displaying the users?" and comments in spanish  and also, the color used to display the users is incorrect.

**Pull request merged**
