### PR TITLE
Delete tracking files

### PR DESCRIPTION
**Pull request by Angel591Diaz**
#### Download the google-service.json file manually.

### CODE REVIEW

**Review by IsmaelMontiel710 — COMMENTED** [review]
LGTM

**Review by MeganPegueros — APPROVED** [review]

**Review by Gavalencia12 — APPROVED** [review]
Ok

**Review by IsmaelMontiel710 — APPROVED** [review]
LGTM

**Comment by Zama15** [comment]
Excellent GW :+1:

**Pull request merged**
