### PR TITLE
Update Terms and Conditions and Add Privacy Policies

### PR DESCRIPTION
**Pull request by MeganPegueros**
### Pull Request: Update Terms and Conditions and Add Privacy Policies #78 

These changes are necessary to provide a better user experience and ensure transparency by connecting related sections of the platform’s legal documentation. 
With the help of my teammates, @Angel591Diaz and @Gavalencia12, we implemented links within the sections that redirect to the privacy policies and terms and conditions for both the seller and user.

## Description

- What changes are being made?
> - Updated and improved Terms and Conditions for Sellers and Users to ensure clarity, professionalism, and alignment with platform policies.
> - Added comprehensive Privacy Policies for Sellers and Users, outlining CarHive's approach to data collection, protection, and user rights.
> - Updated application content to reflect these changes in the "Legal" section.

- Why are these changes necessary?
> - Provide sellers and users with clearer guidelines on the use of the platform.
> - Comply with data protection regulations and establish trust by detailing how CarHive safeguards user data.
> - Enhance the user experience by improving legal documentation clarity and organization.

- How have these changes been tested?
> - Manually reviewed the updated files for errors and typos.
> -  Verified the integration of the new content into the application interface via the "Terms of Use" and "Privacy Policy" sections.
> - Tested all changes in a staging environment to ensure the content renders correctly and aligns with expected behavior.

## Additional Information

- Screenshot: Terms and Conditions for Sellers
image
image
image
image
image

- Screenshot: Privacy Policy for Sellers
image
image
image

- Screenshot: Terms and Conditions for User
image
image
image
image

- Screenshot: Privacy Policy for User
image
image
image

## List of Changes
- [x] Updated fragment_seller_profile_terms.xml with revised terms and responsibilities for sellers.
- [x] Updated fragment_user_profile_terms.xml to reflect clearer usage guidelines.
- [x] Created a fragment_seller_profile_privacy_policy.xml and fragment_user_profile_privacy_policy.xml document covering privacy policies for both sellers and users.
- [x] Implementation of links to the user and seller terms and conditions sections in their respective privacy policies

### CODE REVIEW

**Review by Gavalencia12 — APPROVED** [review]
very good

**Comment by Uli19** [comment]
The alignment of the paragraphs is justified, I recommend that you put it in Align left, and I also think that you should use black for the titles so that it has that color contrast.

**Review by Kamila04 — APPROVED** [review]
Looks good. Good job :+1:

**Comment by MeganPegueros** [comment]
@Uli19 Regarding your comment, using left alignment can be an option, but in most project documents or official documentation, justified alignment is used for greater formality and professionalism.

**Review by Angel591Diaz — APPROVED** [review]
Good Work

**Comment by IsmaelMontiel710** [comment]
LGTM

**Pull request merged**
