### PR TITLE
58 add notifications for vendors users and administrators

### PR DESCRIPTION
**Pull request by Angel591Diaz**
## Pull Request Title

Add Notifications for Seller and Users

## Description

- **What changes are being made?**
This pull request introduces the functionality to add and manage notifications for seller and users. The implementation includes:
- Notifications can now be marked as read/unread.
- Notifications can be deleted with a confirmation dialog.
- Background color dynamically changes based on the read status (`isRead`).
- Enhanced notification UI for better user experience.

- **Why are these changes necessary?**
These changes enhance the system's communication capabilities by providing real-time updates and better management of notifications for different user roles, ensuring that sellers and administrators can respond promptly to relevant events.

- **How have these changes been tested?**
- Manual testing was performed to verify the following:
- Notifications are displayed correctly based on their `isRead` status.
- Deleting a notification works and reflects in the database.
- UI updates dynamically when notifications are read or deleted.
- Navigation works correctly based on the type of notification.

## Additional Information

- **Screenshots**:
1. **Unread Notification**:

2. **Read Notification**:

4. **Delete Confirmation Dialog**:
5. 

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by Kamila04 — APPROVED** [review]
Good job 👍

**Review by Gavalencia12 — APPROVED** [review]
good job

**Comment by IsmaelMontiel710** [comment]
LGTM

**Comment by IsmaelMontiel710** [comment]
@Kamila04 very bad

**Pull request merged**
