### PR TITLE
Seller view redesign completed

### PR DESCRIPTION
**Pull request by Uli19**
**<============== Seller Redesign ==============>**

The seller profile page was redesigned to improve usability, visual appeal, and access to important information. Using an improved view of the components, adding new images and a carousel of comments for the seller.

**What changes are being made?**

An initial section of the seller's rating was added, a score that users give to the seller for their way of negotiating, this was applied at the beginning as one of the initial components for the seller to see when starting their session.
In addition, a section of reviews for the seller was added, this with a horizontal carousel style to make it more pleasant for the seller user.
Finally, the icons and cards from previous versions were resized.

**Why are these changes necessary?**

These changes were applied because a visual improvement of the seller section was needed, adding new information necessary for the seller, but in a way that is not annoying.

**How have these changes been tested?**

Standalone tests were performed using Android devices with the required version

**/////////////     Visual Information     \\\\\\\\\\\\\\**

https://github.com/user-attachments/assets/8e4e06f6-0636-4d08-9681-e7e072893c9a

image 1

image 2

### CODE REVIEW

**Review by Kamila04 — APPROVED** [review]
Good 👍

**Review by Angel591Diaz — APPROVED** [review]
no comments in Spanish

**Comment by Monti710** [comment]
LGTM

**Review by Monti710 — COMMENTED** [review]
LGTM😝

**Review by Monti710 — APPROVED** [review]
LGTM GOOD WORK BRO

**Pull request merged**
